// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmOmCExDUyIOXMXwWYcyGjKToeDXMedB4',
    appId: '1:1042996620318:web:0ba36b7fb489df50e9520f',
    messagingSenderId: '1042996620318',
    projectId: 'dartpr-38fe2',
    authDomain: 'dartpr-38fe2.firebaseapp.com',
    storageBucket: 'dartpr-38fe2.appspot.com',
    measurementId: 'G-JYEQFTYE4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6wEwJ9flKue8xwQYX0IPjZLUAYK3fK-I',
    appId: '1:1042996620318:android:12152fa4ae63e373e9520f',
    messagingSenderId: '1042996620318',
    projectId: 'dartpr-38fe2',
    storageBucket: 'dartpr-38fe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQVlM8ZeENT8EjdhWTa3hTVLi3yNJHwLI',
    appId: '1:1042996620318:ios:cbd1682472cbaa56e9520f',
    messagingSenderId: '1042996620318',
    projectId: 'dartpr-38fe2',
    storageBucket: 'dartpr-38fe2.appspot.com',
    iosClientId: '1042996620318-u2tboe4if14o4t0559hpkekshf9e92me.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQVlM8ZeENT8EjdhWTa3hTVLi3yNJHwLI',
    appId: '1:1042996620318:ios:cbd1682472cbaa56e9520f',
    messagingSenderId: '1042996620318',
    projectId: 'dartpr-38fe2',
    storageBucket: 'dartpr-38fe2.appspot.com',
    iosClientId: '1042996620318-u2tboe4if14o4t0559hpkekshf9e92me.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationTwo',
  );
}
